# Generated by Django 5.1.2 on 2024-11-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='interns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('repo_link', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('task', models.CharField(max_length=50)),
                ('task_assigned_by', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('task_closure_time', models.TimeField()),
                ('next_task', models.CharField(max_length=50)),
                ('next_task_assigned_by', models.CharField(max_length=50)),
            ],
        ),
    ]
