# Generated by Django 5.1.2 on 2024-11-07 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interns',
            name='date',
        ),
        migrations.RemoveField(
            model_name='interns',
            name='next_task',
        ),
        migrations.RemoveField(
            model_name='interns',
            name='next_task_assigned_by',
        ),
        migrations.RemoveField(
            model_name='interns',
            name='task',
        ),
        migrations.RemoveField(
            model_name='interns',
            name='task_assigned_by',
        ),
        migrations.RemoveField(
            model_name='interns',
            name='task_closure_time',
        ),
    ]
