# Generated by Django 5.1.2 on 2024-11-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0003_remove_interns_id_interns_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interns',
            name='task',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='interns',
            name='task_assigned_by',
            field=models.CharField(max_length=50),
        ),
    ]
