# Generated by Django 5.1.2 on 2024-11-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0004_alter_interns_task_alter_interns_task_assigned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='interns',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
